name: CI 

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs: 
  build-test-validate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest tests/

      - name: Validate CloudFormation template with AWS CLI 
        run: |
          aws cloudformation validate-template --template-body file://infra/template.yaml