version = 0.1
[default.deploy.parameters]
stack_name = "lambda-error-analyzer-dev"
resolve_s3 = true
s3_prefix = "lambda-error-analyzer-dev"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "VerifiedSenderEmail=\"eric20050708@gmail.com\" RecipientEmail=\"eric20050708@gmail.com\""
image_repositories = []
